namespace Atc.Rest.Client
{
    /// <summary>
    /// A machine-readable format for specifying errors in HTTP API responses based on https://tools.ietf.org/html/rfc7807.
    /// </summary>
    /// <remarks>
    /// This follow same base structure as Microsoft.AspNetCore.Mvc.ProblemDetails.
    /// </remarks>
    public class ProblemDetails
    {
        /// <summary>
        /// Gets or sets a short, human-readable summary of the problem type.It SHOULD NOT change from occurrence to occurrence
        /// of the problem, except for purposes of localization(e.g., using proactive content negotiation;
        /// see[RFC7231], Section 3.4).
        /// </summary>
        public string Title { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the HTTP status code([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
        /// </summary>
        public int? Status { get; set; }

        /// <summary>
        /// Gets or sets a human-readable explanation specific to this occurrence of the problem.
        /// </summary>
        public string Detail { get; set; } = string.Empty;
    }
}